module.exports = {
    user: {},
    company: {},
    project: {},
    update: {},
    tech: {},
    showcase: {},
    entity: {},
    contact: {},
    member: {},
    route: {},
    task: {},
    account: {},
    transaction: {},
    statement: {},
};
